CREATE TABLE IF NOT EXISTS `users` (
    `id` MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `news` BOOLEAN NOT NULL DEFAULT FALSE ,
    `avatar_path` VARCHAR(255) NULL,
    `salt` VARCHAR(100) NOT NULL
) ENGINE=INNODB;
